test_name: Fluxo de tarefas (To-Dos) com encadeamento e validação

#parametrização
marks:
  - parametrize:
      key: todo_id
      vals:
        - 1
        - 5
        - 15

#estágios
stages:
  - name: Estágio 1 - Buscar tarefa específica
    request:
      url: "https://jsonplaceholder.typicode.com/todos/{todo_id}"
      method: GET

    response:
      status_code: 200
      save:
        json:
          id_do_usuario: userId

  - name: Estágio 2 - Buscar todas as tarefas do usuário
    request:
      url: "https://jsonplaceholder.typicode.com/todos?userId={id_do_usuario}"
      method: GET

    response:
      status_code: 200
      verify_response_with:
        function: utils:validar_lista_tarefas
